# Generated by Django 3.2 on 2021-08-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_super_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='users.Specialization'),
        ),
    ]
